rm "2020-02-02 09-47-14_Start.png"
rm "carbon.png"
rm "career questions for data folks (2).png"
rm "create-new-kedro-project-1.png"
rm "dev.to (4).png"
rm "find-kedro.png"
rm "find-kedro-release-10.png"
rm "find-kedro-release-11.png"
rm "find-kedro-release-9.png"
rm "gh-actions headers-discuss.png"
rm "halftone-simple.png"
rm "kedro-class-hooks.png"
rm "kedro-static-viz-0-3-0-is-out-with-hooks-support.png"
rm "light-blob-alpha.png"
rm "light-blob.png"
rm "pipeline_visualisation (1).png"
rm "Screenshot_20190508-145353.png"
rm "Screenshot_20200211-063919.png"
rm "screenshot_20200527-111836.png"
rm "send-email-with-github-actions-1.png"
rm "subscribe-recaptcha.png"
rm "the-moment-i-realized-the-true-problem.png"
rm "W.png"
