name: 🔗-UrlChecker

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: URLs-checker
        uses: urlstechie/urlchecker-action@0.0.27
        with:
          file_types: "**/*.md"
