# This is a basic workflow to help you get started with Actions

name: 🧪 Test Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - package-update*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://npm.pkg.github.com/
          scope: "@ownername"
      - name: install npm
        run: |
          npm i -g gatsby-cli
          npm install --production
      - name: gatsby build
        run: |
          echo "-----directory structure--------"
          ls
          echo "-----directory structure--------"
          ls src
          echo "-----clean--------"
          gatsby clean
          echo "------building site--------"
          gatsby build
